apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    deployment: {{ .Release.Name }}
spec:
  replicas: {{ .Values.odoo.replicas }}
  selector:
    matchLabels:
      deployment: {{ .Release.Name }}
  template:
    metadata:
      labels:
        deployment: {{ .Release.Name }}
    spec:
      automountServiceAccountToken: false

      containers:
        - name: odoo
          image: odoo:19
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 375m
              ephemeral-storage: 2Gi
              memory: 384Mi
            requests:
              cpu: 50m
              ephemeral-storage: 50Mi
              memory: 256Mi

          command: ["sh", "-c"]
          args:
            - |
              set -e

              BOOTSTRAP_MARKER="/var/lib/odoo/.bootstrapped"

              echo "Waiting for PgBouncer on localhost:5432..."

              until psql "postgresql://odoo:odoo@127.0.0.1:5432/odoo" -c '\q' >/dev/null 2>&1; do
                sleep 2
              done
              echo "PgBouncer is up"

              mkdir -p /var/lib/odoo/extra-addons

              if [ -f "$BOOTSTRAP_MARKER" ]; then
                echo "Already bootstrapped ($BOOTSTRAP_MARKER exists). Skipping bootstrap."
              else
                echo "Bootstrap marker not found. Running first-time bootstrap..."

                echo "Running Odoo init (base module) on 'odoo' database..."
                odoo -c /etc/odoo/odoo.conf -d odoo -i base --stop-after-init

                echo "Setting admin password..."
                echo "u=env['res.users'].search([('login','=','admin')],limit=1); u.password='{{ .Values.odoo.init.adminPassword }}'; env.cr.commit()" \
                | odoo shell -d odoo --no-http --shell-file=/dev/stdin

                echo "Creating bootstrap marker..."
                touch "$BOOTSTRAP_MARKER"

                echo "Bootstrap complete."
              fi

              echo "Starting Odoo..."
              exec odoo -c /etc/odoo/odoo.conf
              
          volumeMounts:
            - name: odoo-pvc
              mountPath: /var/lib/odoo
            - name: odoo-conf
              mountPath: /etc/odoo/odoo.conf
              subPath: odoo.conf

        - name: pgbouncer
          image: edoburu/pgbouncer:1.15.0
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgbouncer-config
              mountPath: /etc/pgbouncer
          command:
            - pgbouncer
            - /etc/pgbouncer/pgbouncer.ini

      volumes:
        - name: odoo-pvc
          persistentVolumeClaim:
            claimName: odoo-{{ include "name" . }}-pvc
        - name: odoo-conf
          configMap:
            name: odoo-{{ .Release.Name }}-odoo-conf
        - name: pgbouncer-config
          configMap:
            name: odoo-{{ .Release.Name }}-pgbouncer-config
