apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: odoo-{{ include "name" . }}-database
  namespace: asset-public-postgres
spec:
  name: odoo-{{ include "name" . }}-database
  owner: postgres-public001-user
  cluster:
    name: {{ .Values.externalDatabase.cluster.name }}
    namespace: {{ .Values.externalDatabase.cluster.namespace }}
    