apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: odoo-{{ include "name" . }}-database
  namespace: {{ .Values.externalDatabase.cluster.namespace }}
spec:
  name: odoo-{{ include "name" . }}-database
  owner: {{ .Values.externalDatabase.username }}
  cluster:
    name: {{ .Values.externalDatabase.cluster.name }}
    namespace: {{ .Values.externalDatabase.cluster.namespace }}
    