Deployment:
- name: urfaclient
  replicas: 2
  imagePullSecrets:
    - registry-login
  containers:
  - name: urfaclient
    image: example.com/example-app:example-tag
    environment:
    - TZ: Asia/Yerevan
    envVarRef:
    - Password: secret://secretname:secretkey

CMS:
- name: example-com
  type: ghost
  expose: service-example-com
  image: ghost:5.40
  replicas: 1
  cache:
    enable: false
  environment:
    - database__client: mysql
    - database__connection__host: db.example.com
    - database__connection__user: user 
    - database__connection__password: password
    - database__connection__database: db
    - url: https://example.com
  persistentVolumeClaim:
    - name: pvc-example-com
      exists: true
      volumepath: /www/example.com
      mountpath: /var/lib/ghost/content
- name: example-com
  type: wordpress
  expose: service-example-com
  image: wordpress:php8.2-apache
  replicas: 1
  cache:
    enable: false
  files:
  - config://wordpress-example-com/usr/local/etc/php/conf.d/wordpress.ini: |
      upload_max_filesize = 256M
      post_max_size = 256M
      max_execution_time = 300    
  environment:
  - WORDPRESS_DB_HOST: db.example.com
  - WORDPRESS_DB_USER: username
  - WORDPRESS_DB_PASSWORD: password
  - WORDPRESS_DB_NAME: db

  persistentVolumeClaim:
  - name: pvc-example-com
    exists: true
    volumepath: /www/example.com
    mountpath: /var/www/html

- name: example-com
  type: dle # datalife engine
  expose: service-example-com
  image: yeranosyanvahan/dle:latest
  replicas: 1
  cache: 
    enable: false
  persistentVolumeClaim:
  - name: pvc-example-com
    exists: true
    volumepath: /www/example.com
    mountpath: /var/www/html

- name: example-com
  type: odoo
  expose: service-example-com
  image: odoo:14.0
  replicas: 1
  cache: 
    enable: false
  persistentVolumeClaim:
  - name: pvc-example-com
    exists: true
    volumepath: /odoo/example.com
    mountpath: /var/lib/odoo
  environment:
  - HOST: db.example.com
  - USER: username
  - PASSWORD: password

DB: 
- name: example-com
  type: mysql
  expose: service-example-com
  image: mysql:5.7
  replicas: 1
  environment:
    - MYSQL_ROOT_PASSWORD: supersecretpassword
  volumeClaimTemplates:
  - metaname: pvc-db-example-com
    mountPath: "/var/lib/mysql"
    size: "80Gi"
    storageClassName: "hostpath"
    accessModes:
      - "ReadWriteOnce"

DNS:
- name: example-com
  type: bind9
  expose: service-example-com
  image: bind9:latest
  replicas: 1
  resources: { requests: { memory: "64Mi", cpu: "250m" }, limits: { memory: "128Mi", cpu: "500m" } }
  files:
    - config://named-conf-dns-example-com/etc/bind/named.conf: |
        acl bogus_networks {
          0.0.0.0/8; 224.0.0.0/3;
        };
        acl private_networks {
          192.168.0.0/24; 10.0.0.0/8; 172.16.0.0/12;
        };
        options {
          forwarders {
            194.61.89.131;
            8.8.8.8;
            1.1.1.1;
          };
          allow-query { private_networks; };
          allow-recursion { private_networks; };
          blackhole { bogus_networks; };
        };
        zone "example.com" IN {
          type master;
          file "/etc/bind/example.com,zone";
          allow-query { any; };
        };
    - config://example-com-dns-example-com/etc/bind/example.com.zone: |
        example.com
        ;
        ; BIND data file for techtuts.local zone
        ;
        $TTL    604800
        $ORIGIN techtuts.local.
        @       IN      SOA     ns.example.com. root.example.com. (
                                      1         ; Serial
                                604800         ; Refresh
                                  86400         ; Retry
                                2419200         ; Expire
                                604800 )       ; Negative Cache TTL
        ;name server records
                IN      NS      ns.example.com.
        ;name server host records
        ns      IN      A       192.168.0.40
        ;host records for other devices
        srv1            IN      A       192.168.0.40

Ingress:
  name: example-com
  crtissuername: general-issuer
  middlewares:
    - https-only
  vhosts:
  - hostname: example.com
    tls: enable
    forward:
      host: example-com
      port: 80

Issuer:
  name: general-issuer
  email: email@example.com

Middleware:
- name: https-only
  spec:
    redirectScheme:
      scheme: https
      permanent: true
- name: basic-auth
  spec:
    basicAuth:
      secret: htpasswd-vahan

PersistentVolumeClaim:
- name: pvc-example-com
  accessModes:
    - ReadWriteOnce
  storage:
    storageClassName: nfs
    readOnly: false
    size: 400Mi
    path: /var/nfs
    server: db.example.com
  
- name: pvc-example-com
  accessModes:
    - ReadWriteOnce
  storage:
    storageClassName: longhorn
    readOnly: false
    size: 400Mi
    path: /var/nfs

- name: pvc-example-com
  accessModes:
    - ReadWriteOnce
  storage:
    storageClassName: hostpath
    readOnly: false
    size: 400Mi
    path: /var/nfs
  