{{- $configs := list}}
{{- if kindIs "map" .Values.config -}}
 {{- $configs = append $configs .Values.config  }}
{{- else if kindIs "slice" .Values.config }}
 {{- $configs = .Values.config }}
{{- end}}
{{- range $configs }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ $.Values.namespace }}
  name: {{ .name }}
data: {{ .data | toYaml | nindent 1 }}
---
{{- end}}
