{{- if .Values.helmchart -}}
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
 name: {{.Values.helmchart.name}}
 namespace: {{.Values.namespace}}
spec: {{ .Values.helmchart.spec | toYaml | nindent 1 }}
{{- end}}
