{{- if .Values.issuer -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  namespace: {{.Values.namespace}}
  name: {{ .Values.issuer.name }}
spec:
  acme:
    email: {{ .Values.issuer.email }}
    privateKeySecretRef:
      name: letsencrypt-production
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress: {}
{{- end -}}
