{{- if .Values.pvc -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{.Values.namespace}}
  name: {{.Values.pvc.name}}
spec:
  accessModes:
    {{- range .Values.pvc.accessModes }}
    - {{ . }}
    {{- end}}
  resources:
    requests:
      storage: {{.Values.pvc.storage}}
  {{- if .Values.pvc.pv }} {{- if .Values.pvc.pv.name}}
  volumeName: {{.Values.pvc.pv.name}}
  {{else}}
  volumeName: {{.Values.pvc.name}}
  {{- end}}{{- end}}
  storageClassName: {{.Values.pvc.storageClassName}}
{{- end}}
