apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: wordpress-{{ include "name" . }}-database
  namespace: {{ .Release.Namespace }}
spec:
  mariaDbRef:
    name: {{ .Values.externalDatabaseMariadb.mariaDbRef.name }}
    namespace: {{ .Values.externalDatabaseMariadb.mariaDbRef.namespace }}
  characterSet: utf8
  collate: utf8_general_ci
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name:  wordpress-{{ include "name" . }}-user
  namespace: {{ .Release.Namespace }}
spec:
  mariaDbRef:
    name: {{ .Values.externalDatabaseMariadb.mariaDbRef.name }}
    namespace: {{ .Values.externalDatabaseMariadb.mariaDbRef.namespace }}
  passwordSecretKeyRef:
    name: mariadb-{{ include "name" . }}-secret
    key: mariadb-password
  maxUserConnections: 20
  host: {{ (default "%" .Values.wordpress.host) | quote }}
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: wordpress-{{ include "name" . }}-grant
  namespace: {{ .Release.Namespace }}
spec:
  mariaDbRef:
    name: {{ .Values.externalDatabaseMariadb.mariaDbRef.name }}
    namespace: {{ .Values.externalDatabaseMariadb.mariaDbRef.namespace }}
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
    - "DELETE"
    - "CREATE"
    - "ALTER"
    - "INDEX"
    #- "ALL PRIVILEGES"
  database: wordpress-{{ include "name" . }}-database
  username: wordpress-{{ include "name" . }}-user
  grantOption: false
  host: {{ (default "%" .Values.wordpress.host) | quote }}
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Connection
metadata:
  name: wordpress-{{ include "name" . }}-connection
spec:
  mariaDbRef:
    name: {{ .Values.externalDatabaseMariadb.mariaDbRef.name }}
    namespace: {{ .Values.externalDatabaseMariadb.mariaDbRef.namespace }}
  username: wordpress-{{ include "name" . }}-user
  passwordSecretKeyRef:
    name: mariadb-{{ include "name" . }}-secret
    key: mariadb-password
  database: wordpress-{{ include "name" . }}-database
  secretName: wordpress-{{ include "name" . }}-connection
  secretTemplate:
    metadata:
      labels:
        k8s.mariadb.com/connection:  wordpress-{{ include "name" . }}-connection
    usernameKey: username
    passwordKey: password
    hostKey: host
    portKey: port
    databaseKey: database
