apiVersion: v1
kind: Secret
metadata:
  name: mariadb-{{ .Values.hostname }}-secret
  namespace: {{ .Release.Namespace }}
labels:
    k8s.mariadb.com/watch: ""
type: Opaque
data:
  mariadb-password: {{ randAlphaNum 32 | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-{{ .Values.hostname }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  wordpress-password: {{ randAlphaNum 32 | b64enc | quote }}