apiVersion: v1
kind: Secret
metadata:
  name: mariadb-{{ .Values.hostname }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
      k8s.mariadb.com/watch: ""
data:
  {{- if .Release.IsInstall }}
  mariadb-password: {{ randAlphaNum 32 | b64enc | quote  }}
  {{ else }}
  mariadb-password:  {{ index (lookup "v1" "Secret" .Release.Namespace "mariadb-{{ .Values.hostname }}-secret").data "mariadb-password" }}
  {{ end }}
