{{- if not (lookup "v1" "Secret" .Release.Namespace (printf "mariadb-%s-secret" .Values.hostname)) }}
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-{{ .Values.hostname }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": "keep"
  labels:
    k8s.mariadb.com/watch: ""
data:
  mariadb-password: {{ randAlphaNum 32 | b64enc | quote }}
{{ end }}
