{{- if not (lookup "v1" "secret" .Release.Namespace "mariadb-{{ .Values.hostname }}-secret") -}}
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-{{ .Values.hostname }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
      k8s.mariadb.com/watch: ""
data:
  mariadb-password: {{ randAlphaNum 32 | b64enc | quote  }}
{{ end }}
