externalDatabase:
  username: user
  password: password
  cluster:
    name: postgres-public000-asset
    namespace: asset-public-postgres
ingress:
  enabled: true
  hostname: od308.web.miom.am
  wwwPrefix: false
  annotations:
    kubernetes.io/ingress.class: traefik
persistence:
  accessModes:
    - ReadWriteOnce
  size: 12Gi
  storageClass: local-path
odoo:
  init:
    adminPassword: admin
  odooConf:
    options: |-
      workers: 0 
  replicas: 1