{{- range .Values.Certificate -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}
spec:
  dnsNames:
    {{- range .hostnames }}
    - {{ . }}
    {{- end}}
  secretName: {{ .secret }}
  issuerRef:
    kind: Issuer
    name: {{ .issuer }}
{{- end}}
