{{- $pvc := list}}
{{- if kindIs "map" .Values.PersistentVolumeClaim -}}
 {{- $pvc = append $pvc .Values.PersistentVolumeClaim  }}
{{- else if kindIs "slice" .Values.PersistentVolumeClaim }}
 {{- $pvc = .Values.PersistentVolumeClaim }}
{{- end}}

{{- range $pvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
spec:
  accessModes:
    {{- range .accessModes }}
    - {{ . }}
    {{- end}}
  resources:
    requests:
      storage: {{.storage}}
  {{- if .PersistentVolume }} {{- if .PersistentVolume.name}}
  volumeName: {{ .PersistentVolume.name }}
  {{else}}
  volumeName: {{ .name }}
  {{- end}}{{- end}}
  storageClassName: {{ .storageClassName }}
---
{{- if .PersistentVolume -}}
apiVersion: v1
kind: PersistentVolume
metadata:
    {{- if .PersistentVolume.name}}
    name: {{.PersistentVolume.name}}
    {{else}}
    name: {{.name}}
    {{- end}}
spec:
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    {{- range .accessModes }}
    - {{ . }}
    {{- end}}
  capacity:
    storage: {{.storage}}
  storageClassName: {{.storageClassName}}
  # custom defined
  {{.PersistentVolume | toYaml | indent 2 | trim}}

{{- end}}
---
{{- end}}


