{{- if  .Values.Service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Service.name }}
spec:
  selector:
    {{- .Values.Service.selector  | toYaml | nindent 3 }}
  ports:
  {{- range .Values.Service.expose }}{{- range $name_port, $targetport := .}}
  {{- $portname := (split " " $name_port)._0 }}
  {{- $port := (split " " $name_port)._1 }}
  - name: {{ quote $portname }}
    port: {{ if eq $port "" }} {{ $portname }} {{ else }} {{ $port }} {{ end }}
    protocol: TCP
    targetPort: {{  $targetport }}
  {{- end}} {{- end}}
{{- end}}
