{{- $configs := list}}
{{- if kindIs "map" .Values.ConfigMap -}}
 {{- $configs = append $configs .Values.ConfigMap  }}
{{- else if kindIs "slice" .Values.ConfigMap }}
 {{- $configs = .Values.ConfigMap }}
{{- end}}
{{- range $configs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
data: {{ .data | toYaml | nindent 1 }}
---
{{- end}}
