{{- if .Values.ExternalSecret -}}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.ExternalSecret.name }}
spec:
  {{- unset (unset  ( deepCopy .Values.ExternalSecret ) "name")  "extract" | toYaml | nindent 2 }}
  target:
    {{ if .Values.ExternalSecret.extract.template -}}
    template:
      {{- .Values.ExternalSecret.extract.template | toYaml | nindent 5 }}
    {{ end -}}
    name: {{ .Values.ExternalSecret.extract.target }}
  dataFrom:
   - extract:
      key: {{ .Values.ExternalSecret.extract.source }}

{{- end -}}
