{{- if .Values.PersistentVolumeClaim -}}{{- if .Values.PersistentVolumeClaim.PersistentVolume -}}
apiVersion: v1
kind: PersistentVolume
metadata:
    {{- if .Values.PersistentVolumeClaim.PersistentVolume.name}}
    name: {{.Values.PersistentVolumeClaim.PersistentVolume.name}}
    {{else}}
    name: {{.Values.PersistentVolumeClaim.name}}
    {{- end}}
spec:
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    {{- range .Values.PersistentVolumeClaim.accessModes }}
    - {{ . }}
    {{- end}}
  capacity:
    storage: {{.Values.PersistentVolumeClaim.storage}}
  storageClassName: {{.Values.PersistentVolumeClaim.storageClassName}}
  # custom defined
  {{.Values.PersistentVolumeClaim.PersistentVolume | toYaml | indent 2 | trim}}

{{- end}}{{- end}}
