{{- $secrets := list}}
{{- if kindIs "map" .Values.Secret -}}
 {{- $secrets = append $secrets .Values.Secret  }}
{{- else if kindIs "slice" .Values.Secret }}
 {{- $secrets = .Values.Secret }}
{{- end}}

{{- range $secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
{{- if .type }}
type: {{ .type }}
{{- else }}
type: Opaque
{{- end }}
stringData: {{ .data | toYaml | nindent 1 }}
---
{{- end}}
