name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.3  # Replace with the Helm version you need

      - name: Install Chart Releaser
        run: |
          curl -sSL https://github.com/helm/chart-releaser/releases/download/v1.6.0/chart-releaser_1.6.0_linux_amd64.tar.gz | tar xz
          sudo mv cr /usr/local/bin

      - name: Run Chart Releaser
        run: |
          cr upload --config .github/chart-releaser.yaml
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
