name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.3  # Adjust to your desired Helm version

      - name: Package Helm Charts
        run: |
          mkdir -p .cr-release-packages
          helm package chartologist --destination .cr-release-packages
          helm package harchitect --destination .cr-release-packages
          helm package mariadb-wordpress-chart --destination .cr-release-packages

      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages
          git worktree add gh-pages origin/gh-pages

      - name: Update Helm Chart Repository
        run: |
          cp -r .cr-release-packages/* gh-pages/
          cd gh-pages
          git add .
          git commit -m "Update Helm charts"
          git push origin gh-pages
