name: Release Charts

on:
  push:
    branches:
      - main


jobs:
  package-helm-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Helm
        uses: azure/setup-helm@v3
      
      - name: Package Helm Charts
        run: |
          mkdir -p ./output
          for chart in */templates; do
            helm package $chart --destination ./output
          done
      
      - name: Publish Helm Charts to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
